services:
  - type: web
    name: 8bits-battle-api
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: HOST_KEY
        sync: false
